var Vips=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var m=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,r=ba&&self.name?.startsWith("em-pthread");m.dynamicLibraries=m.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];m.workaroundCors&&(m.mainScriptUrlOrBlob=m.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var ca=[],da="./this.program";ba&&(_scriptName=self.location.href);var fa="";
function ha(a){return m.locateFile?m.locateFile(a,fa):fa+a}var ja,ka;if(aa||ba){try{fa=(new URL(".",_scriptName)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ja=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var la=console.log.bind(console),w=console.error.bind(console),ma=[],na,oa,pa=!1,qa;class x extends Error{}
class ra extends x{}class sa extends x{constructor(a){super(a);this.xa=a;a=ta(a);this.name=a[0];this.message=a[1]}}var ua,va,wa={},xa;
if(r){var ya=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.W;if("load"===d){let e=[];self.onmessage=f=>e.push(f);xa=()=>{postMessage({W:"loaded"});for(let f of e)a(f);self.onmessage=a};ma=c.Db;wa=c.nc;for(const f of c.Ob)if(!m[f]||m[f].proxy)m[f]=(...g)=>{postMessage({W:"callHandler",Nb:f,xb:g})},"print"==f&&(la=m[f]),"printErr"==f&&(w=m[f]);za=c.tc;Ba();oa=c.uc;Ca();Da()}else if("run"===d){Ea(c.Z);Fa(c.Z,0,0,1,0,0);Ga();Ha(c.Z);ya||(Ia(),ya=!0);try{Ja(c.qc,
c.Fa)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ya&&Ka():d&&(w(`worker: received unknown command ${d}`),w(c)))}catch(e){throw La(),e;}}self.onmessage=a}var za,y,z,A,C,D,E,Na,Oa,F,Pa,Qa=!1,Ra=!1;function Ba(){var a=za.buffer;y=new Int8Array(a);A=new Int16Array(a);z=new Uint8Array(a);C=new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);Na=new Float32Array(a);Oa=new Float64Array(a);F=new BigInt64Array(a);Pa=new BigUint64Array(a)}var Sa=[];
function Ta(){Qa=!0;r?xa():(Ua(Sa),m.noFSInit||FS.Ja||FS.init(),Va.__wasm_call_ctors(),Ua(Wa),FS.eb=!1)}function G(a){m.onAbort?.(a);a="Aborted("+a+")";w(a);pa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");va?.(a);throw a;}var Xa;async function Ya(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==Xa&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Za(a,b){try{var c=await Ya(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),G(d)}}async function $a(a){var b=Xa;if(!na)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return Za(b,a)}
function ab(){I={__assert_fail:bb,__call_sighandler:cb,__cxa_begin_catch:db,__cxa_end_catch:eb,__cxa_find_matching_catch_2:fb,__cxa_find_matching_catch_3:gb,__cxa_rethrow:hb,__cxa_throw:ib,__cxa_uncaught_exceptions:jb,__heap_base:kb,__indirect_function_table:lb,__lsan_ignore_object:mb,__memory_base:nb,__pthread_create_js:ob,__resumeException:pb,__stack_high:qb,__stack_low:rb,__stack_pointer:sb,__syscall_dup:tb,__syscall_faccessat:ub,__syscall_fcntl64:vb,__syscall_fstat64:wb,__syscall_ftruncate64:xb,
__syscall_getcwd:yb,__syscall_ioctl:zb,__syscall_lstat64:Ab,__syscall_newfstatat:Bb,__syscall_openat:Cb,__syscall_poll:Db,__syscall_rmdir:Eb,__syscall_stat64:Fb,__syscall_unlinkat:Gb,__table_base:Hb,_abort_js:Ib,_dlopen_js:Jb,_dlsym_catchup_js:Kb,_dlsym_js:Lb,_embind_finalize_value_object:Mb,_embind_register_arithmetic_vector:Nb,_embind_register_bigint:Ob,_embind_register_bool:Pb,_embind_register_class:Qb,_embind_register_class_class_function:Rb,_embind_register_class_constructor:Sb,_embind_register_class_function:Tb,
_embind_register_class_property:Ub,_embind_register_emval:Vb,_embind_register_enum:Wb,_embind_register_enum_value:Xb,_embind_register_float:Yb,_embind_register_function:Zb,_embind_register_integer:$b,_embind_register_memory_view:ac,_embind_register_std_string:bc,_embind_register_std_wstring:cc,_embind_register_value_object:dc,_embind_register_value_object_field:ec,_embind_register_void:fc,_emscripten_dlopen_js:gc,_emscripten_dlsync_threads:hc,_emscripten_dlsync_threads_async:ic,_emscripten_get_dynamic_libraries_js:jc,
_emscripten_init_main_thread_js:kc,_emscripten_notify_mailbox_postmessage:lc,_emscripten_receive_on_main_thread_js:mc,_emscripten_runtime_keepalive_clear:nc,_emscripten_thread_cleanup:oc,_emscripten_thread_exit_joinable:pc,_emscripten_thread_mailbox_await:Ha,_emscripten_thread_set_strongref:qc,_emscripten_throw_longjmp:rc,_emval_create_invoker:sc,_emval_decref:tc,_emval_get_global:uc,_emval_get_module_property:vc,_emval_get_property:wc,_emval_incref:xc,_emval_instanceof:yc,_emval_invoke:zc,_emval_is_number:Ac,
_emval_is_string:Bc,_emval_new_cstring:Cc,_emval_run_destructors:Dc,_emval_set_property:Ec,_emval_typeof:Fc,_gmtime_js:Gc,_localtime_js:Hc,_mmap_js:Ic,_munmap_js:Jc,_tzset_js:Kc,clock_time_get:Lc,emscripten_check_blocking_allowed:Mc,emscripten_date_now:Nc,emscripten_err:Oc,emscripten_exit_with_live_runtime:Pc,emscripten_get_heap_max:Qc,emscripten_get_now:Rc,emscripten_num_logical_cores:Sc,emscripten_promise_destroy:Tc,emscripten_promise_resolve:Uc,emscripten_resize_heap:Vc,environ_get:Wc,environ_sizes_get:Xc,
exit:Yc,fd_close:Zc,fd_fdstat_get:$c,fd_read:ad,fd_seek:bd,fd_write:cd,ffi_call_js:dd,heif_color_conversion_options_ext_copy:ed,heif_color_conversion_options_ext_free:fd,heif_encoding_options_alloc:gd,heif_encoding_options_free:hd,heif_error_success:jd,heif_image_get_bits_per_pixel_range:kd,heif_image_get_chroma_format:ld,heif_image_get_nclx_color_profile:md,heif_image_get_plane_readonly2:nd,heif_image_release:od,heif_nclx_color_profile_free:pd,heif_tai_clock_info_release:qd,heif_tai_timestamp_packet_alloc:rd,
heif_tai_timestamp_packet_copy:sd,heif_tai_timestamp_packet_release:td,invoke_di:ud,invoke_dii:vd,invoke_diii:wd,invoke_diiiii:xd,invoke_fiii:yd,invoke_i:zd,invoke_ii:Ad,invoke_iii:Bd,invoke_iiid:Cd,invoke_iiii:Dd,invoke_iiiii:Ed,invoke_iiiiid:Fd,invoke_iiiiii:Gd,invoke_iiiiiii:Hd,invoke_iiiiiiii:Id,invoke_iiiiiiiiiii:Jd,invoke_iiiiiiiiiiii:Kd,invoke_iiiiiiiiiiiii:Ld,invoke_iiiiij:Md,invoke_ji:Nd,invoke_jiiii:Od,invoke_v:Pd,invoke_vi:Qd,invoke_vid:Rd,invoke_viddi:Sd,invoke_vii:Td,invoke_viid:Ud,invoke_viidd:Vd,
invoke_viiddi:Wd,invoke_viidi:Xd,invoke_viii:Yd,invoke_viiid:Zd,invoke_viiidddddi:$d,invoke_viiiddddi:ae,invoke_viiidddi:be,invoke_viiiddi:ce,invoke_viiidi:de,invoke_viiii:ee,invoke_viiiii:fe,invoke_viiiiii:ge,invoke_viiiiiii:he,invoke_viiiiiiii:ie,invoke_viiiiiiiii:je,invoke_viiiiiiiiii:ke,invoke_viiiiiiiiiii:le,invoke_viiiiiiiiiiii:me,invoke_viiiiiiiiiiiii:ne,invoke_viiiiiiiiiiiiiii:oe,memory:za,proc_exit:pe,random_get:qe};return{env:I,wasi_snapshot_preview1:I,"GOT.mem":new Proxy(I,re),"GOT.func":new Proxy(I,
re)}}
async function Ca(){function a(d,e){Va=d.exports;Va=se(Va,1024);var f=te(e);ue(Va);ve("__main__",0,I);we();xe(Va._emscripten_tls_init,d.exports,f);Sa.push(Va.__wasm_apply_data_relocs);oa=e;d=Va;ye=d.__getTypeName;Ia=d._embind_initialize_bindings;ze=d.pthread_self;Ae=d.malloc;m._main=d.main;J=d.free;Be=d.fflush;Ce=d.calloc;m._emscripten_builtin_free=d.emscripten_builtin_free;De=d.emscripten_builtin_memalign;m._emscripten_builtin_malloc=d.emscripten_builtin_malloc;Ee=d.__funcs_on_exit;m.___libc_calloc=d.__libc_calloc;
m.___libc_free=d.__libc_free;m.___libc_malloc=d.__libc_malloc;Fe=d.__dl_seterr;Ge=d._emscripten_dlsync_self_async;He=d._emscripten_dlsync_self;Ie=d._emscripten_proxy_dlsync_async;Je=d._emscripten_proxy_dlsync;Ke=d._emscripten_find_dylib;Fa=d._emscripten_thread_init;La=d._emscripten_thread_crashed;Le=d._emscripten_run_js_on_main_thread;Me=d._emscripten_thread_free_data;Ne=d._emscripten_thread_exit;m._strndup=d.strndup;Oe=d._emscripten_check_mailbox;m.__ZdaPvm=d._ZdaPvm;m.__Znaj=d._Znaj;m.__ZnajSt11align_val_t=
d._ZnajSt11align_val_t;m.__Znwj=d._Znwj;m.__ZnwjSt11align_val_t=d._ZnwjSt11align_val_t;m.___libc_realloc=d.__libc_realloc;m._emscripten_builtin_calloc=d.emscripten_builtin_calloc;m._emscripten_builtin_realloc=d.emscripten_builtin_realloc;m._malloc_size=d.malloc_size;m._malloc_usable_size=d.malloc_usable_size;m._reallocf=d.reallocf;K=d.setThrew;Pe=d._emscripten_tempret_set;Qe=d.emscripten_stack_set_limits;O=d._emscripten_stack_restore;Re=d._emscripten_stack_alloc;P=d.emscripten_stack_get_current;Se=
d.__cxa_increment_exception_refcount;Te=d.__cxa_decrement_exception_refcount;Ue=d.__get_exception_message;Ve=d.__cxa_can_catch;We=d.__cxa_get_exception_ptr;return Va}var b=ab();if(m.instantiateWasm)return new Promise(d=>{m.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(r){var c=new WebAssembly.Instance(oa,ab());return a(c,oa)}Xa??=ha("vips.wasm");return function(d){return a(d.instance,d.module)}(await $a(b))}var Ye=a=>{if(!(a instanceof Xe||"unwind"==a))throw a;};
class Xe{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Q=0,Ze=a=>{a.terminate();a.onmessage=()=>{}},ef=a=>{var b=$e[a];af.delete(a);a in bf&&bf[a].resolve();a=b.Z;delete $e[a];cf.push(b);df.splice(df.indexOf(b),1);b.Z=0;Me(a)},Ua=a=>{for(;0<a.length;)a.shift()(m)},ff=[],gf=a=>{af.add(a);a in bf&&bf[a].resolve()},hf=0,jf=null,kf=()=>{hf--;m.monitorRunDependencies?.(hf);if(0==hf&&jf){var a=jf;jf=null;a()}},lf=()=>{hf++;m.monitorRunDependencies?.(hf)},of=a=>{0==cf.length&&(mf(),nf(cf[0]));var b=cf.pop();if(!b)return 6;df.push(b);$e[a.Z]=b;b.Z=a.Z;b.postMessage({W:"run",
qc:a.pc,Fa:a.Fa,Z:a.Z},a.rb);return 0},cf=[],df=[],pf=[],$e={};function qf(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)mf();ff.push(async()=>{var b=rf();lf("loading-workers");await b;kf("loading-workers")});bf={};af=new Set}var sf=()=>{for(var a of df)Ze(a);for(a of cf)Ze(a);cf=[];df=[];$e={}};function Ga(){pf.forEach(a=>a())}
var nf=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.W;if(g.Ea&&g.Ea!=ze()){var h=$e[g.Ea];h?h.postMessage(g,g.rb):w(`Internal error! Worker sent a message "${f}" to target pthread ${g.Ea}, but that thread no longer exists!`)}else if("checkMailbox"===f)Ka();else if("spawnThread"===f)of(g);else if("cleanupThread"===f)tf(()=>ef(g.Ta));else if("markAsFinished"===f)gf(g.Ta);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)m[g.Nb](...g.xb);
else f&&w(`worker sent an unknown command ${f}`)};a.onerror=f=>{w(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)m.propertyIsEnumerable(e)&&c.push(e);a.postMessage({W:"load",Ob:c,tc:za,uc:oa,Db:ma,nc:wa})});async function rf(){if(!r)return Promise.all(cf.map(nf))}
function mf(){var a=_scriptName;m.mainScriptUrlOrBlob&&(a=m.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{name:"em-pthread"});cf.push(a)}var af,bf,R=(a,b,...c)=>{for(var d=2*c.length,e=P(),f=Re(8*d),g=f>>3,h=0;h<c.length;h++){var k=c[h];"bigint"==typeof k?(F[g+2*h]=1n,F[g+2*h+1]=k):(F[g+2*h]=0n,Oa[g+2*h+1]=k)}a=Le(a,0,d,f,b);O(e);return a};function pe(a){if(r)return R(0,1,a);qa=a;uf||0<Q||(sf(),m.onExit?.(a),pa=!0);throw new Xe(a);}pe.g="vi";
function vf(a){if(r)return R(1,0,a);Yc(a)}var Yc=a=>{qa=a;if(r)throw vf(a),"unwind";if(!(uf||0<Q||r)){Ee();FS.Ja=!1;Be(0);for(var b of FS.streams)b&&FS.close(b);sf();Ra=!0}pe(a)};Yc.g="vi";var tf=a=>{if(!Ra&&!pa)try{if(a(),!(Ra||uf||0<Q))try{r?ze()&&Ne(qa):Yc(qa)}catch(b){Ye(b)}}catch(b){Ye(b)}},wf=a=>{Q+=1;setTimeout(()=>{--Q;tf(a)},1E4)},xf=[],yf={},zf=!1;
function Af(){function a(){zf=document.pointerLockElement===m.canvas}if(!Bf){Bf=!0;xf.push({canHandle:function(c){return!m.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Cf(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Cf(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var k=new Image;k.onload=()=>{var l=document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,
0,0);URL.revokeObjectURL(f);g(c)};k.onerror=()=>{w(`Image ${f} could not be decoded`);h()};k.src=f})}});xf.push({canHandle:function(c){return!m.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:Cf(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=function(){if(!g){w(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var l="",n=0,p=0,q=0;q<c.length;q++)for(n=n<<8|c[q],p+=8;6<=p;){var t=n>>p-6&63;p-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[t]}2==p?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&3)<<4],l+="=="):4==p&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;wf(()=>{f(k)})})}});var b=m.canvas;b&&(document.addEventListener("pointerlockchange",a,
!1),m.elementPointerLock&&b.addEventListener("click",c=>{!zf&&m.canvas.requestPointerLock&&(m.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Cf(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Df={},Bf,Ef={},Ff=new Set(["__lsan_ignore_object","__lsan_ignore_object"]),re={get(a,b){(a=Ef[b])||(a=Ef[b]=new WebAssembly.Global({value:"i32",mutable:!0}));Ff.has(b)||(a.required=!0);return a}},Gf=[];function Ea(a){var b=E[a+52>>2];Qe(b,b-E[a+56>>2]);O(b)}
var Hf=new TextDecoder,If=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Jf=(a,b=0,c)=>{c=If(a,b,c);return Hf.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},te=a=>{function b(){for(var p=0,q=1;;){var t=a[f++];p+=(t&127)*q;q*=128;if(!(t&128))break}return p}function c(){var p=b();f+=p;return Jf(a,f-p,p)}function d(){for(var p=b(),q=[];p--;)q.push(c());return q}function e(p,q){if(p)throw Error(q);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var h=c();e("dylink.0"!==h)}for(h={Oa:[],qb:new Set,sb:new Set,nb:[]};f<g;){var k=a[f++],l=b();if(1===k)h.Na=b(),h.Wb=b(),h.ua=b(),h.Pc=b();else if(2===k)h.Oa=d();else if(3===
k)for(k=b();k--;){l=c();var n=b();n&256&&h.qb.add(l)}else if(4===k)for(k=b();k--;)c(),l=c(),n=b(),1==(n&3)&&h.sb.add(l);else 5===k?h.nb=d():f+=l}return h},Kf=[],lb=new WebAssembly.Table({initial:5886,element:"anyfunc"}),S=a=>{var b=Kf[a];b||(Kf[a]=b=lb.get(a));return b},Ja=(a,b)=>{uf=Q=0;He();a=S(a)(b);uf||0<Q?qa=a:Ne(a)},ve=(a,b,c)=>{c={Ca:Infinity,name:a,exports:c,global:!0};Lf[a]=c;void 0!=b&&(Mf[b]=c);return c},Lf={},Mf={},kb=3678160,Nf=(a,b)=>Math.ceil(a/b)*b,Of=a=>{if(Qa)return Ce(a,1);var b=
kb;kb=a=b+16*Math.ceil(a/16);Ef.__heap_base.value=a;return b},Pf=a=>{const b=a.length;return[b%128|128,b>>7,...a]},Qf={i:127,p:127,j:126,f:125,d:124,e:111},Rf=a=>Pf(Array.from(a,b=>Qf[b])),Tf=(a,b)=>{if(Sf)for(var c=a;c<a+b;c++){var d=S(c);d&&Sf.set(d,c)}},Sf,Uf=a=>{Sf||(Sf=new WeakMap,Tf(0,lb.length));return Sf.get(a)||0},Vf=[],Wf=(a,b)=>{var c=Uf(a);if(c)return c;c=Vf.length?Vf.pop():lb.grow(1);try{lb.set(c,a),Kf[c]=lb.get(c)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,
109,1,0,0,0,1,...Pf([1,96,...Rf(b.slice(1)),...Rf("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;lb.set(c,b);Kf[c]=lb.get(c)}Sf.set(a,c);return c},se=(a,b,c)=>{var d={},e;for(e in a){var f=a[e];"object"==typeof f&&(f=f.value);"number"==typeof f&&(f+=b);d[e]=f}for(var g in d){a=g;if("__cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(a)||
a.startsWith("__em_js__"))continue;a=d[g];let h,k;(h=Ef)[k=g]||(h[k]=new WebAssembly.Global({value:"i32",mutable:!0}));if(c||0==Ef[g].value)"function"==typeof a?Ef[g].value=Wf(a):"number"==typeof a?Ef[g].value=a:w(`unhandled export type for '${g}': ${typeof a}`)}return d},Xf=a=>{a=I[a];return!a||a.G?!1:!0},Yf=(a,b=[])=>S(a)(...b),Zf=a=>(b,...c)=>{var d=P();try{return Yf(b,c)}catch(e){O(d);if(!(e instanceof x))throw e;K(1,0);if("j"==a[0])return 0n}},bg=a=>{var b;Xf(a)?b=I[a]:a.startsWith("invoke_")?
b=I[a]=Zf(a.split("_")[1]):a.startsWith("__cxa_find_matching_catch_")&&(b=I[a]=(...c)=>$f(c));return{Sa:b,name:a}},Wa=[],T=(a,b,c)=>a?Hf.decode(z.slice(a,If(z,a,b,c))):"",fg=(a,b,c,d,e)=>{function f(){function h(v,B){function L(Aa,ea){Aa=[];for(var Ma=0;16>Ma;Ma++)if(-1!=ea.indexOf("$"+Ma))Aa.push("$"+Ma);else break;Aa=Aa.join(",");cg[H]=eval(`(${Aa}) => { ${ea} };`)}function M(Aa,ea,Ma){var ag=[];ea=ea.slice(1,-1);if("void"!=ea){ea=ea.split(",");for(var Zh in ea){var $h=ea[Zh].split(" ").pop();ag.push($h.replace("*",
""))}}q[Aa]=eval(`(${ag}) => ${Ma};`)}!r&&c&&(wa[c]=v);Tf(p,g.ua);q=se(B.exports,n);b.wb||dg();if("__start_em_asm"in q){var H=q.__start_em_asm;for(v=q.__stop_em_asm;H<v;){var ia=T(H);L(H,ia);H=z.indexOf(0,H)+1}}for(var N in q)N.startsWith("__em_js__")&&(H=q[N],ia=T(H),v=ia.split("<::>"),M(N.replace("__em_js__",""),v[0],v[1]),delete q[N]);xe(q._emscripten_tls_init,B.exports,g);k&&((B=q.__wasm_apply_data_relocs)&&(Qa?B():Sa.push(B)),(B=q.__wasm_call_ctors)&&(Qa?B():Wa.push(B)));return q}var k=!e||!y[e+
8];if(k){var l=Math.pow(2,g.Wb),n=g.Na?Nf(Of(g.Na+l),l):0,p=g.ua?lb.length:0;e&&(y[e+8]=1,E[e+12>>2]=n,D[e+16>>2]=g.Na,E[e+20>>2]=p,D[e+24>>2]=g.ua)}else n=E[e+12>>2],p=E[e+20>>2];g.ua&&lb.grow(g.ua);var q;l=new Proxy({},{get(v,B){switch(B){case "__memory_base":return n;case "__table_base":return p}if(B in I&&!I[B].G)return I[B];if(!(B in v)){var L;v[B]=(...M)=>{if(!L){var H=bg(B).Sa;!H&&d&&(H=d[B]);H||=q[B];L=H}return L(...M)}}return v[B]}});Ff=g.sb;var t={"GOT.mem":new Proxy({},re),"GOT.func":new Proxy({},
re),env:l,wasi_snapshot_preview1:l};if(b.J)return(async()=>{var v;a instanceof WebAssembly.Module?v=new WebAssembly.Instance(a,t):{module:a,instance:v}=await WebAssembly.instantiate(a,t);return h(a,v)})();l=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);var u=new WebAssembly.Instance(l,t);return h(l,u)}var g=te(a);b={...b,jc:{ac:c,dc:g.nb}};if(b.J)return g.Oa.reduce((h,k)=>h.then(()=>eg(k,b,d)),Promise.resolve()).then(f);g.Oa.forEach(h=>eg(h,b,d));return f()},ue=a=>{var b,c;for([b,c]of Object.entries(a))Xf(b)||
(I[b]=c)},gg=async a=>{a=await ja(a);return new Uint8Array(a)},hg=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ig=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=hg(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},jg=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},kg=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],lg=(a,b)=>ig(a+"/"+b),mg=a=>{var b=P();a=a();O(b);return a},ng=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},og=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|
g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},pg=a=>{var b=ng(a)+1,c=Re(b);og(a,z,c,b);return c},qg=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),rg=a=>{(rg=qg())(a)},sg=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
hg(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},tg=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=sg(a).slice(1);b=sg(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},ug=[],vg=a=>{var b=Array(ng(a)+1);a=og(a,b,0,b.length);b.length=
a;return b},wg=[];function xg(a,b){wg[a]={input:[],output:[],da:b};FS.registerDevice(a,yg)}
var yg={open(a){var b=wg[a.node.sa];if(!b)throw new FS.h(43);a.C=b;a.seekable=!1},close(a){a.C.da.za(a.C)},za(a){a.C.da.za(a.C)},read(a,b,c,d){if(!a.C||!a.C.da.cb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.da.cb(a.C)}catch(h){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.aa=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.da.Qa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.C.da.Qa(a.C,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.O=a.node.N=Date.now());return e}},zg={cb(){a:{if(!ug.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ug=vg(a)}a=ug.shift()}return a},Qa(a,b){null===b||10===b?(la(Jf(a.output)),a.output=[]):0!=b&&a.output.push(b)},za(a){0<a.output?.length&&(la(Jf(a.output)),a.output=[])},Rb(){return{Ac:25856,Cc:5,zc:191,Bc:35387,yc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0]}},Sb(){return 0},Tb(){return[24,80]}},Ag={Qa(a,b){null===b||10===b?(w(Jf(a.output)),a.output=[]):0!=b&&a.output.push(b)},za(a){0<a.output?.length&&(w(Jf(a.output)),a.output=[])}},Bg=a=>{a=65536*Math.ceil(a/65536);var b=De(65536,a);b&&z.fill(0,b,b+a);return b},U={Y:null,mount(){return U.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);U.Y||(U.Y={dir:{node:{T:U.m.T,V:U.m.V,ja:U.m.ja,ca:U.m.ca,rename:U.m.rename,unlink:U.m.unlink,
rmdir:U.m.rmdir,ta:U.m.ta,symlink:U.m.symlink},stream:{llseek:U.o.llseek}},file:{node:{T:U.m.T,V:U.m.V},stream:{llseek:U.o.llseek,read:U.o.read,write:U.o.write,ka:U.o.ka,ma:U.o.ma}},link:{node:{T:U.m.T,V:U.m.V,readlink:U.m.readlink},stream:{}},Va:{node:{T:U.m.T,V:U.m.V},stream:FS.zb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=U.Y.dir.node,c.o=U.Y.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=U.Y.file.node,c.o=U.Y.file.stream,c.H=0,c.u=null):FS.isLink(c.mode)?(c.m=U.Y.link.node,c.o=U.Y.link.stream):
FS.isChrdev(c.mode)&&(c.m=U.Y.Va.node,c.o=U.Y.Va.stream);c.aa=c.O=c.N=Date.now();a&&(a.u[b]=c,a.aa=a.O=a.N=c.aa);return c},Jc(a){return a.u?a.u.subarray?a.u.subarray(0,a.H):new Uint8Array(a.u):new Uint8Array(0)},m:{T(a){var b={};b.Bb=FS.isChrdev(a.mode)?a.id:1;b.Qb=a.id;b.mode=a.mode;b.Xb=1;b.uid=0;b.Mb=0;b.sa=a.sa;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.H:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.aa=new Date(a.aa);b.O=new Date(a.O);b.N=new Date(a.N);b.yb=4096;b.Ua=Math.ceil(b.size/
b.yb);return b},V(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.H!=b&&(0==b?(a.u=null,a.H=0):(c=a.u,a.u=new Uint8Array(b),c&&a.u.set(c.subarray(0,Math.min(b,a.H))),a.H=b)))},ja(){U.Ga||(U.Ga=new FS.h(44),U.Ga.stack="<generic error, no stack>");throw U.Ga;},ca(a,b,c,d){return U.createNode(a,b,c,d)},rename(a,b,c){try{var d=Cg(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);Dg(d)}delete a.parent.u[a.name];b.u[c]=a;
a.name=c;b.N=b.O=a.parent.N=a.parent.O=Date.now()},unlink(a,b){delete a.u[b];a.N=a.O=Date.now()},rmdir(a,b){var c=Cg(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.N=a.O=Date.now()},ta(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){var f=a.node.u;if(e>=a.node.H)return 0;a=Math.min(a.node.H-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=
0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.O=a.N=Date.now();if(b.subarray&&(!a.u||a.u.subarray)){if(f)return a.u=b.subarray(c,c+d),a.H=d;if(0===a.H&&0===e)return a.u=b.slice(c,c+d),a.H=d;if(e+d<=a.H)return a.u.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.u?a.u.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.u,a.u=new Uint8Array(f),0<a.H&&a.u.set(g.subarray(0,a.H),0));if(a.u.subarray&&b.subarray)a.u.set(b.subarray(c,c+d),e);else for(f=
0;f<d;f++)a.u[e+f]=b[c+f];a.H=Math.max(a.H,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.H);if(0>b)throw new FS.h(28);return b},ka(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||!a||a.buffer!==y.buffer){d=!0;e=Bg(b);if(!e)throw new FS.h(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);y.set(a,e)}}else d=!1,e=a.byteOffset;return{s:e,ea:d}},ma(a,b,c,d){U.o.write(a,b,0,d,c,!1);
return 0}}},Eg=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Fg=async(a,b)=>{"undefined"!=typeof Df&&Af();for(var c of xf)if(c.canHandle(b))return c.handle(a,b);return a},Gg=async(a,b,c,d,e,f,g,h)=>{var k=b?sg(ig(a+"/"+b)):a,l=`cp ${k}`;lf(l);try{var n=c;"string"==typeof c&&(n=await gg(c));n=await Fg(n,k);h?.();f||FS.createDataFile(a,b,n,d,e,g)}finally{kf(l)}};
function Cg(a,b){var c=FS.isDir(a.mode)?(c=Hg(a,"x"))?c:a.m.ja?0:2:54;if(c)throw new FS.h(c);for(c=FS.X[Ig(a.id,b)];c;c=c.la){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ja(a,b)}function Dg(a){var b=Ig(a.parent.id,a.name);if(FS.X[b]===a)FS.X[b]=a.la;else for(b=FS.X[b];b;){if(b.la===a){b.la=a.la;break}b=b.la}}function Ig(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.X.length}function Jg(a){var b=Ig(a.parent.id,a.name);a.la=FS.X[b];FS.X[b]=a}
function Kg(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hg(a,b){if(FS.eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lg(a,b){if(!FS.isDir(a.mode))return 54;try{return Cg(a,b),20}catch(c){}return Hg(a,"wx")}
function Mg(a,b,c){try{var d=Cg(a,b)}catch(e){return e.A}if(a=Hg(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.oa(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Ng(a,b){if(!a)throw new FS.h(b);return a}function V(a){a=FS.bb(a);if(!a)throw new FS.h(8);return a}function Og(a,b=-1){a=Object.assign(new FS.ub,a);if(-1==b)a:{for(b=0;b<=FS.vb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.ba=b;return FS.streams[b]=a}
function Pg(a,b=-1){a=Og(a,b);a.o?.Ec?.(a);return a}function Qg(a,b,c){var d=a?.o.V;a=d?a:b;d??=b.m.V;Ng(d,63);d(a,c)}function Rg(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.pa)}return b}function Sg(a){var b={xc:4096,Hc:4096,Ua:1E6,wc:5E5,vc:5E5,files:FS.Pa,Fc:FS.Pa-1,Ic:42,flags:2,Mc:255};a.m.pb&&Object.assign(b,a.m.pb(a.mount.Zb.root));return b}function Tg(a,b,c,d){Qg(a,b,{mode:c&4095|b.mode&-4096,N:Date.now(),Za:d})}
function Ug(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=Hg(b,"w");if(d)throw new FS.h(d);Qg(a,b,{size:c,timestamp:Date.now()})}function Vg(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=ig(a+"/"+b);return FS.create(b,Eg(c,d))}
function Wg(a){if(!(a.Ub||a.Vb||a.link||a.u))if("undefined"!=typeof XMLHttpRequest)G("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.u=ka(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,pa:[],Ya:{},streams:[],Pa:1,X:null,Wa:"/",Ja:!1,eb:!0,Gb:null,Da:0,mb:{},h:class{name="ErrnoError";constructor(a){this.A=a}},ub:class{P={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},tb:class{m={};o={};U=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Pa++;this.name=b;this.mode=c;this.sa=d;this.aa=
this.O=this.N=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Vb(){return FS.isDir(this.mode)}get Ub(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.ya??(b.ya=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=jg(e),FS.oa(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=ig(e+"/"+a[f]);try{d=Cg(d,a[f])}catch(h){if(44===h?.A&&g&&b.Yb)return{path:e};throw h;}!d.U||g&&!b.ya||(d=d.U.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=jg(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.oa(a))return a=a.mount.ib,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.tb(a,b,c,d);Jg(a);return a},oa(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},vb:4096,bb:a=>FS.streams[a],zb:{open(a){a.o=FS.Ib(a.node.sa).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ma:a=>a>>
8,Kc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Ya[a]={o:b}},Ib:a=>FS.Ya[a],syncfs(a,b){function c(g){FS.Da--;return b(g)}function d(g){if(g){if(!d.Eb)return d.Eb=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Da++;1<FS.Da&&w(`warning: ${FS.Da} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Rg(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);
if(!d&&c){var e=FS.lookupPath(c,{ya:!1});c=e.path;e=e.node;if(e.U)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,Zb:b,ib:c,pa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.U=b,e.mount&&e.mount.pa.push(b));return a},unmount(a){a=FS.lookupPath(a,{ya:!1});if(!a.node.U)throw new FS.h(28);a=a.node;var b=a.U,c=Rg(b);Object.keys(FS.X).forEach(d=>{for(d=FS.X[d];d;){var e=d.la;c.includes(d.mount)&&Dg(d);d=e}});a.U=null;a.mount.pa.splice(a.mount.pa.indexOf(b),1)},ja(a,b){return a.m.ja(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=kg(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=Lg(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},pb(a){return Sg(FS.lookupPath(a,{follow:!0}).node)},Oc(a){return Sg(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Lc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.A)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!sg(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=kg(b);var d=Lg(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=jg(a),d=jg(b),e=kg(a),f=kg(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);
var k=Cg(h,e);a=tg(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=tg(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var l=Cg(g,f)}catch(n){}if(k!==l){b=FS.isDir(k.mode);if(e=Mg(h,e,b))throw new FS.h(e);if(e=l?Mg(g,f,b):Lg(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);if(k.U||l&&l.U)throw new FS.h(10);if(g!==h&&(e=Hg(h,"w")))throw new FS.h(e);Dg(k);try{h.m.rename(k,g,f),k.parent=g}catch(n){throw n;}finally{Jg(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=kg(a);var c=Cg(b,a),
d=Mg(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.U)throw new FS.h(10);b.m.rmdir(b,a);Dg(c)},ta(a){a=FS.lookupPath(a,{follow:!0}).node;return Ng(a.m.ta,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=kg(a);var c=Cg(b,a),d=Mg(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.U)throw new FS.h(10);b.m.unlink(b,a);Dg(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Ng(a.m.T,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Tg(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=V(a);Tg(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;Qg(null,a,{timestamp:Date.now(),Za:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=V(a);Qg(a,a.node,{timestamp:Date.now(),Za:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Ug(null,a,b)},ftruncate(a,b){a=V(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);Ug(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Ng(a.m.V,63)(a,{aa:b,O:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
a=FS.lookupPath(a,{follow:!(b&131072),Yb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==Kg(g)||g&576)?31:Hg(e,Kg(g)):44)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=Og({node:d,path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,
sc:[],error:!1});e.o.open&&e.o.open(e);f&&FS.chmod(d,c&511);!m.logReadFiles||b&1||a in FS.mb||(FS.mb[a]=1);return e},close(a){if(null===a.ba)throw new FS.h(8);a.Ha&&(a.Ha=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.ba]=null}a.ba=null},llseek(a,b,c){if(null===a.ba)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.sc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);if(null===
a.ba)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.ba)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&a.flags&
1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ka(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ka)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ka(a,b,c,d,e)},ma(a,b,c,d,e){return a.o.ma?a.o.ma(a,b,c,d,e):0},Ka(a,b,c){if(!a.o.Ka)throw new FS.h(59);return a.o.Ka(a,b,c)},readFile(a,b={}){b.flags=
b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&G(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Jf(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(vg(b)));ArrayBuffer.isView(b)?FS.write(a,b,0,b.byteLength,void 0,c.Dc):G("Unsupported data type");FS.close(a)},cwd:()=>FS.Wa,
chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);var b=Hg(a.node,"x");if(b)throw new FS.h(b);FS.Wa=a.path},init(a,b,c){FS.Ja=!0;a??=m.stdin;b??=m.stdout;c??=m.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",
1);FS.open("/dev/stderr",1)},Gc(a,b){a=FS.analyzePath(a,b);return a.$a?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={oa:!1,$a:!1,error:0,name:null,path:null,object:null,$b:!1,cc:null,bc:null};try{c=FS.lookupPath(a,{parent:!0}),d.$b=!0,d.cc=c.path,d.bc=c.node,d.name=kg(a),c=FS.lookupPath(a,{follow:!b}),d.$a=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.oa="/"===c.path}catch(e){d.error=e.A}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);
for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=ig(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.A)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?ig(a+"/"+b):a);a=Eg(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,b,c,d){a=lg("string"==typeof a?a:FS.getPath(a),
b);b=Eg(!!c,!!d);var e;(e=FS.createDevice).Ma??(e.Ma=64);e=FS.makedev(FS.createDevice.Ma++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=0,n=0;n<k;n++){try{var p=c()}catch(q){throw new FS.h(29);}if(void 0===p&&0===l)throw new FS.h(6);if(null===p||void 0===p)break;l++;g[h+n]=p}l&&(f.node.aa=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(n){throw new FS.h(29);}k&&(f.node.O=f.node.N=Date.now());return l}});return FS.mkdev(a,
b,e)},createLazyFile(a,b,c,d,e){function f(p,q,t,u,v){p=p.node.u;if(v>=p.length)return 0;u=Math.min(p.length-v,u);if(p.slice)for(var B=0;B<u;B++)q[t+B]=p[v+B];else for(B=0;B<u;B++)q[t+B]=p.get(v+B);return u}class g{Ia=!1;P=[];na=void 0;hb=0;gb=0;get(p){if(!(p>this.length-1||0>p)){var q=p%this.ob;return this.na(p/this.ob|0)[q]}}rc(p){this.na=p}jb(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);200<=p.status&&300>p.status||304===p.status||G("Couldn't load "+c+". Status: "+p.status);var q=
Number(p.getResponseHeader("Content-length")),t,u=(t=p.getResponseHeader("Accept-Ranges"))&&"bytes"===t;p=(t=p.getResponseHeader("Content-Encoding"))&&"gzip"===t;var v=1048576;u||(v=q);var B=this;B.rc(L=>{var M=L*v,H=(L+1)*v-1;H=Math.min(H,q-1);if("undefined"==typeof B.P[L]){var ia=B.P;M>H&&G("invalid range ("+M+", "+H+") or no bytes requested!");H>q-1&&G("only "+q+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);q!==v&&N.setRequestHeader("Range","bytes="+M+"-"+H);
N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);200<=N.status&&300>N.status||304===N.status||G("Couldn't load "+c+". Status: "+N.status);M=void 0!==N.response?new Uint8Array(N.response||[]):vg(N.responseText||"");ia[L]=M}"undefined"==typeof B.P[L]&&G("doXHR failed!");return B.P[L]});if(p||!q)v=q=1,v=q=this.na(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");this.hb=q;this.gb=v;this.Ia=
!0}get length(){this.Ia||this.jb();return this.hb}get ob(){this.Ia||this.jb();return this.gb}}if("undefined"!=typeof XMLHttpRequest){ba||G("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var k=void 0}else k=c,h=void 0;var l=Vg(a,b,d,e);h?l.u=h:k&&(l.u=null,l.url=k);Object.defineProperties(l,{H:{get:function(){return this.u.length}}});var n={};Object.keys(l.o).forEach(p=>{var q=l.o[p];n[p]=(...t)=>{Wg(l);return q(...t)}});
n.read=(p,q,t,u,v)=>{Wg(l);return f(p,q,t,u,v)};n.ka=(p,q,t)=>{Wg(l);var u=Bg(q);if(!u)throw new FS.h(48);f(p,y,u,q,t);return{s:u,ea:!0}};l.o=n;return l}},Xg=(a,b)=>{if(Qa){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.dc||[]).map(d=>{var e=b?.ac;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",jg(e)):d});return mg(()=>{var d=Re(512),e=pg(c.join(":")),f=pg(a);return(d=Ke(d,e,f,512))?T(d):void 0})}};
function eg(a,b={global:!0,qa:!0},c,d){function e(){var k=wa[a];if(k)return b.J?Promise.resolve(k):k;if(d){k=E[d+28>>2];var l=E[d+32>>2];if(k&&l)return k=y.slice(k,k+l),b.J?Promise.resolve(k):k}if(k=Xg(a,b.jc))return k=FS.readFile(k,{encoding:"binary"}),b.J?Promise.resolve(k):k;k=ha(a);if(b.J)return gg(k);if(!ka)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return ka(k)}function f(){var k=yf[a];return k?b.J?Promise.resolve(k):k:b.J?e().then(l=>fg(l,
b,a,c,d)):fg(e(),b,a,c,d)}function g(k){h.global?ue(k):c&&Object.assign(c,k);h.exports=k}var h=Lf[a];if(h)return b.global?h.global||(h.global=!0,ue(h.exports)):c&&Object.assign(c,h.exports),b.qa&&Infinity!==h.Ca&&(h.Ca=Infinity),h.Ca++,d&&(Mf[d]=h),b.J?Promise.resolve(!0):!0;h=ve(a,d,"loading");h.Ca=b.qa?Infinity:1;h.global=b.global;if(b.J)return f().then(k=>{g(k);return!0});g(f());return!0}
var dg=()=>{var a,b;for([a,b]of Object.entries(Ef))if(0==b.value){var c=bg(a).Sa;if(c||b.required)if("function"==typeof c)b.value=Wf(c,c.g);else if("number"==typeof c)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c}`);}},we=async()=>{if(ma.length){lf("loadDylibs");for(var a of ma)await eg(a,{J:!0,global:!0,qa:!0,wb:!0});dg();kf("loadDylibs")}else dg()},uf=!1,xe=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.qb.forEach(g=>f[g]=b[g]);se(f,e,!0)}}pf.push(d);Qa&&d()},bb=(a,b,c,d)=>
G(`Assertion failed: ${T(a)}, at: `+[b?T(b):"unknown filename",c,d?T(d):"unknown function"]);bb.g="vppip";var cb=(a,b)=>S(a)(b);cb.g="vpi";var Yg=[],Zg=0,db=a=>{var b=new $g(a);0==y[b.s+12]&&(y[b.s+12]=1,Zg--);y[b.s+13]=0;Yg.push(b);Se(a);return We(a)};db.g="pp";var ah=0,eb=()=>{K(0,0);var a=Yg.pop();Te(a.xa);ah=0};eb.g="v";class $g{constructor(a){this.xa=a;this.s=a-24}init(a,b){E[this.s+16>>2]=0;E[this.s+4>>2]=a;E[this.s+8>>2]=b}}
var $f=a=>{var b=ah?.xa;if(!b)return Pe(0),0;var c=new $g(b);E[c.s+16>>2]=b;var d=E[c.s+4>>2];if(!d)return Pe(0),b;for(var e of a){if(0===e||e===d)break;if(Ve(e,d,c.s+16))return Pe(e),b}Pe(d);return b},fb=()=>$f([]);fb.g="p";var gb=a=>$f([a]);gb.g="pp";var hb=()=>{var a=Yg.pop();a||G("no exception to throw");var b=a.xa;0==y[a.s+13]&&(Yg.push(a),y[a.s+13]=1,y[a.s+12]=0,Zg++);ah=new sa(b);throw ah;};hb.g="v";var ib=(a,b,c)=>{(new $g(a)).init(b,c);ah=new sa(a);Zg++;throw ah;};ib.g="vppp";
var jb=()=>Zg;jb.g="i";function mb(...a){return I.__lsan_ignore_object(...a)}mb.G=!0;var nb=new WebAssembly.Global({value:"i32",mutable:!1},1024);function bh(a,b,c,d){return r?R(2,1,a,b,c,d):ob(a,b,c,d)}var ob=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return bh(a,b,c,d);a={pc:c,Z:a,Fa:d,rb:e};return r?(a.W="spawnThread",postMessage(a,e),0):of(a)};ob.g="ipppp";var pb=a=>{ah||=new sa(a);throw ah;};pb.g="vp";
var qb=3678160,rb=3416016,sb=new WebAssembly.Global({value:"i32",mutable:!0},3678160),ch=5;function dh(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():V(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function eh(a,b){E[a>>2]=b.Bb;E[a+4>>2]=b.mode;E[a+8>>2]=b.Xb;E[a+12>>2]=b.uid;E[a+16>>2]=b.Mb;E[a+20>>2]=b.sa;F[a+24>>3]=BigInt(b.size);D[a+32>>2]=4096;D[a+36>>2]=b.Ua;var c=b.aa.getTime(),d=b.O.getTime(),e=b.N.getTime();F[a+40>>3]=BigInt(Math.floor(c/1E3));E[a+48>>2]=c%1E3*1E6;F[a+56>>3]=BigInt(Math.floor(d/1E3));E[a+64>>2]=d%1E3*1E6;F[a+72>>3]=BigInt(Math.floor(e/1E3));E[a+80>>2]=e%1E3*1E6;F[a+88>>3]=BigInt(b.Qb);return 0}var fh=void 0;
function tb(a){if(r)return R(3,1,a);try{var b=V(a);return Pg(b).ba}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}tb.g="ii";function ub(a,b,c,d){if(r)return R(4,1,a,b,c,d);try{b=T(b);b=dh(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Hg(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}ub.g="iipii";var gh=()=>{var a=D[+fh>>2];fh+=4;return a};
function vb(a,b,c){if(r)return R(5,1,a,b,c);fh=c;try{var d=V(a);switch(b){case 0:var e=gh();if(0>e)break;for(;FS.streams[e];)e++;return Pg(d,e).ba;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=gh(),d.flags|=e,0;case 12:return e=gh(),A[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}vb.g="iiip";
function wb(a,b){if(r)return R(6,1,a,b);try{var c=V(a),d=c.node,e=c.o.T;a=e?c:d;e??=d.m.T;Ng(e,63);var f=e(a);return eh(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.A}}wb.g="iip";function xb(a,b){if(r)return R(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}xb.g="iij";
function yb(a,b){if(r)return R(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=ng(c)+1;if(b<d)return-68;og(c,z,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.A}}yb.g="ipp";
function zb(a,b,c){if(r)return R(9,1,a,b,c);fh=c;try{var d=V(a);switch(b){case 21509:return d.C?0:-59;case 21505:if(!d.C)return-59;if(d.C.da.Rb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=gh();D[e>>2]=25856;D[e+4>>2]=5;D[e+8>>2]=191;D[e+12>>2]=35387;for(var f=0;32>f;f++)y[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.C?0:-59;case 21506:case 21507:case 21508:if(!d.C)return-59;if(d.C.da.Sb)for(e=gh(),a=[],f=0;32>f;f++)a.push(y[e+f+17]);
return 0;case 21519:if(!d.C)return-59;e=gh();return D[e>>2]=0;case 21520:return d.C?-28:-59;case 21537:case 21531:return e=gh(),FS.Ka(d,b,e);case 21523:if(!d.C)return-59;d.C.da.Tb&&(f=[24,80],e=gh(),A[e>>1]=f[0],A[e+2>>1]=f[1]);return 0;case 21524:return d.C?0:-59;case 21515:return d.C?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.A}}zb.g="iiip";
function Ab(a,b){if(r)return R(10,1,a,b);try{return a=T(a),eh(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Ab.g="ipp";function Bb(a,b,c,d){if(r)return R(11,1,a,b,c,d);try{b=T(b);var e=d&256;b=dh(a,b,d&4096);return eh(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}Bb.g="iippi";
function Cb(a,b,c,d){if(r)return R(12,1,a,b,c,d);fh=d;try{b=T(b);b=dh(a,b);var e=d?gh():0;return FS.open(b,c,e).ba}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}Cb.g="iipip";function Db(a,b,c){if(r)return R(13,1,a,b,c);try{for(var d=c=0;d<b;d++){var e=a+8*d,f=A[e+4>>1],g=32,h=FS.bb(D[e>>2]);h&&(g=ch,h.o.fc&&(g=h.o.fc(h,-1)));(g&=f|24)&&c++;A[e+6>>1]=g}return c}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.A}}Db.g="ipii";
function Eb(a){if(r)return R(14,1,a);try{return a=T(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.A}}Eb.g="ip";function Fb(a,b){if(r)return R(15,1,a,b);try{return a=T(a),eh(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Fb.g="ipp";
function Gb(a,b,c){if(r)return R(16,1,a,b,c);try{b=T(b);b=dh(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.A}}Gb.g="iipi";var Hb=new WebAssembly.Global({value:"i32",mutable:!1},1),Ib=()=>G("");Ib.g="v";
var hh=a=>{var b=P();a=pg(a);Fe(a,0);O(b)},ih=(a,b)=>{var c=T(a+36),d=D[a+4>>2];c=ig(c);var e=!!(d&256),f=e?null:{};d={global:e,qa:!!(d&4096),J:b.J};if(b.J)return eg(c,d,f,a);try{return eg(c,d,f,a)}catch(g){return hh(`Could not load dynamic lib: ${c}\n${g}`),0}},Jb=a=>ih(a,{J:!1});Jb.g="pp";var Kb=(a,b)=>{a=Mf[a].exports;b=Object.keys(a)[b];b=a[b];return Wf(b,b.g)};Kb.g="ppi";
var Lb=(a,b,c)=>{b=T(b);var d=Mf[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].G)return hh(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=Uf(b))?b=d:(b=Wf(b,b.g),E[c>>2]=a));return b};Lb.g="pppp";var jh={},kh=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function lh(a){return this.B(E[a>>2])}
var mh={},nh={},oh={},ph=class extends Error{constructor(a){super(a);this.name="InternalError"}},rh=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new ph("Mismatched type converter count");for(var k=0;k<a.length;++k)qh(a[k],h[k])}a.forEach(h=>oh[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,k)=>{nh.hasOwnProperty(h)?e[k]=nh[h]:(f.push(h),mh.hasOwnProperty(h)||(mh[h]=[]),mh[h].push(()=>{e[k]=nh[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Mb=a=>{var b=jh[a];delete jh[a];var c=
b.Ra,d=b.$,e=b.ab,f=e.map(g=>g.Lb).concat(e.map(g=>g.lc));rh([a],f,g=>{var h={};e.forEach((k,l)=>{var n=g[l],p=k.na,q=k.Kb,t=g[l+e.length],u=k.kc,v=k.mc;h[k.Fb]={read:B=>n.B(p(q,B)),write:(B,L)=>{var M=[];u(v,B,t.I(M,L));kh(M)},optional:g[l].optional}});return[{name:b.name,B:k=>{var l={},n;for(n in h)l[n]=h[n].read(k);d(k);return l},I:(k,l)=>{for(var n in h)if(!(n in l||h[n].optional))throw new TypeError(`Missing field: "${n}"`);var p=c();for(n in h)h[n].write(p,l[n]);null!==k&&k.push(d,p);return p},
R:lh,L:d}]})};Mb.g="vp";var W=a=>{for(var b="";;){var c=z[a++];if(!c)return b;b+=String.fromCharCode(c)}},X=class extends Error{constructor(a){super(a);this.name="BindingError"}},sh=a=>{throw new X(a);};function th(a,b,c={}){var d=b.name;if(!a)throw new X(`type "${d}" must have a positive integer typeid pointer`);if(nh.hasOwnProperty(a)){if(c.Pb)return;throw new X(`Cannot register type '${d}' twice`);}nh[a]=b;delete oh[a];mh.hasOwnProperty(a)&&(b=mh[a],delete mh[a],b.forEach(e=>e()))}
function qh(a,b,c={}){return th(a,b,c)}
var Nb=(a,b,c,d,e)=>{b=W(b);if(d)a:switch(c){case 4:d=Na;break a;case 8:d=Oa;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?y:z;break a;case 2:d=e?A:C;break a;case 4:d=e?D:E;break a;case 8:d=e?F:Pa;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);qh(a,{name:b,B:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+E[h>>2]));J(h);return k},I:(h,k)=>{"number"==typeof k&&(k=[k]);if(!Array.isArray(k))throw new X(`Cannot pass non-array to C++ vector type ${b}`);
k=Array.prototype.concat.apply([],k);var l=k.length,n=Math.max(4,c),p=Ae(n+l*c);n=p+n>>g;E[p>>2]=l;f.set(k,n);null!==h&&h.push(J,p);return p},R:lh,L(h){J(h)}})};Nb.g="vpppii";
var uh=(a,b,c)=>{switch(b){case 1:return c?d=>y[d]:d=>z[d];case 2:return c?d=>A[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>F[d>>3]:d=>Pa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ob=(a,b,c,d,e)=>{b=W(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}qh(a,{name:b,B:f,I:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},R:uh(b,c,!d),L:null})};Ob.g="vpppjj";
var Pb=(a,b,c,d)=>{b=W(b);qh(a,{name:b,B:function(e){return!!e},I:function(e,f){return f?c:d},R:function(e){return this.B(z[e])},L:null})};Pb.g="vppii";
var vh=a=>{throw new X(a.l.D.v.name+" instance already deleted");},wh=!1,xh=!1,yh=()=>{},zh=a=>{if(wh)return zh=b=>b.deleteLater(),zh(a);if("undefined"===typeof FinalizationRegistry)return zh=b=>b,a;xh=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.K?b.S.$(b.K):b.D.v.$(b.s))});zh=b=>{var c=b.l;c.K&&xh.register(b,{l:c},b);return b};yh=b=>{xh.unregister(b)};return zh(a)},Ah=[],Bh=()=>{for(;Ah.length;){var a=Ah.pop();a.l.ia=!1;a["delete"]()}},Ch;function Dh(){}
var Eh=(a,b)=>Object.defineProperty(b,"name",{value:a}),Fh={},Gh=(a,b,c)=>{if(void 0===a[b].F){var d=a[b];a[b]=function(...e){if(!a[b].F.hasOwnProperty(e.length))throw new X(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].F})!`);return a[b].F[e.length].apply(this,e)};a[b].F=[];a[b].F[d.ga]=d}},Hh=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].F&&void 0!==m[a].F[c])throw new X(`Cannot register public name '${a}' twice`);Gh(m,a,a);if(m[a].F.hasOwnProperty(c))throw new X(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
m[a].F[c]=b}else m[a]=b,m[a].ga=c},Ih=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Jh(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.fa=c;this.$=d;this.M=e;this.Hb=f;this.va=g;this.Cb=h;this.hc=[]}
var Kh=(a,b,c)=>{for(;b!==c;){if(!b.va)throw new X(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.va(a);b=b.M}return a},Lh=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Mh(a,b){if(null===b){if(this.La)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new X(`Cannot pass "${Lh(b)}" as a ${this.name}`);if(!b.l.s)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);return Kh(b.l.s,b.l.D.v,this.v)}
function Nh(a,b){if(null===b){if(this.La)throw new X(`null is not a valid ${this.name}`);if(this.Ba){var c=this.Ra();null!==a&&a.push(this.$,c);return c}return 0}if(!b||!b.l)throw new X(`Cannot pass "${Lh(b)}" as a ${this.name}`);if(!b.l.s)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Aa&&b.l.D.Aa)throw new X(`Cannot convert argument of type ${b.l.S?b.l.S.name:b.l.D.name} to parameter type ${this.name}`);c=Kh(b.l.s,b.l.D.v,this.v);if(this.Ba){if(void 0===b.l.K)throw new X("Passing raw pointer to smart pointer is illegal");
switch(this.oc){case 0:if(b.l.S===this)c=b.l.K;else throw new X(`Cannot convert argument of type ${b.l.S?b.l.S.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.K;break;case 2:if(b.l.S===this)c=b.l.K;else{var d=b.clone();c=this.ic(c,Oh(()=>d["delete"]()));null!==a&&a.push(this.$,c)}break;default:throw new X("Unsupporting sharing policy");}}return c}
function Ph(a,b){if(null===b){if(this.La)throw new X(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new X(`Cannot pass "${Lh(b)}" as a ${this.name}`);if(!b.l.s)throw new X(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.Aa)throw new X(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return Kh(b.l.s,b.l.D.v,this.v)}
var Qh=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=Qh(a,b,c.M);return null===a?null:c.Cb(a)},Rh={},Sh=(a,b)=>{if(void 0===b)throw new X("ptr should not be undefined");for(;a.M;)b=a.va(b),a=a.M;return Rh[b]},Th=(a,b)=>{if(!b.D||!b.s)throw new ph("makeClassHandle requires ptr and ptrType");if(!!b.S!==!!b.K)throw new ph("Both smartPtrType and smartPtr must be specified");b.count={value:1};return zh(Object.create(a,{l:{value:b,writable:!0}}))};
function Uh(a,b,c,d,e,f,g,h,k,l,n){this.name=a;this.v=b;this.La=c;this.Aa=d;this.Ba=e;this.ec=f;this.oc=g;this.lb=h;this.Ra=k;this.ic=l;this.$=n;e||void 0!==b.M?this.I=Nh:(this.I=d?Mh:Ph,this.L=null)}var Vh=(a,b,c)=>{if(!m.hasOwnProperty(a))throw new ph("Replacing nonexistent public symbol");void 0!==m[a].F&&void 0!==c?m[a].F[c]=b:(m[a]=b,m[a].ga=c)},Y=(a,b)=>{a=W(a);var c=S(b);if("function"!=typeof c)throw new X(`unknown function pointer with signature ${a}: ${b}`);return c};
class Wh extends Error{}
var Xh=a=>{a=ye(a);var b=W(a);J(a);return b},Yh=(a,b)=>{function c(f){e[f]||nh[f]||(oh[f]?oh[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Wh(`${a}: `+d.map(Xh).join([", "]));},Qb=(a,b,c,d,e,f,g,h,k,l,n,p,q)=>{n=W(n);f=Y(e,f);h&&=Y(g,h);l&&=Y(k,l);q=Y(p,q);var t=Ih(n);Hh(t,function(){Yh(`Cannot construct ${n} due to unbound types`,[d])});rh([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.v;var B=v.fa}else B=Dh.prototype;u=Eh(n,function(...ia){if(Object.getPrototypeOf(this)!==L)throw new X(`Use 'new' to construct ${n}`);
if(void 0===M.ha)throw new X(`${n} has no accessible constructor`);var N=M.ha[ia.length];if(void 0===N)throw new X(`Tried to invoke ctor of ${n} with invalid number of parameters (${ia.length}) - expected (${Object.keys(M.ha).toString()}) parameters instead!`);return N.apply(this,ia)});var L=Object.create(B,{constructor:{value:u}});u.prototype=L;var M=new Jh(n,u,L,q,v,f,h,l);if(M.M){var H;(H=M.M).wa??(H.wa=[]);M.M.wa.push(M)}v=new Uh(n,M,!0,!1,!1);H=new Uh(n+"*",M,!1,!1,!1);B=new Uh(n+" const*",M,
!1,!0,!1);Fh[a]={pointerType:H,Ab:B};Vh(t,u);return[v,H,B]})};Qb.g="vppppppppppppp";function ai(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].L)return!0;return!1}
function bi(a,b,c,d,e,f){var g=b.length;if(2>g)throw new X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=ai(b);c=!b[0].fb;var l=b[0],n=b[1];d=[a,sh,d,e,kh,l.B.bind(l),n?.I.bind(n)];for(e=2;e<g;++e)l=b[e],d.push(l.I.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].L&&d.push(b[e].L);k=ai(b);e=b.length-2;n=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),l.push(`arg${g}Wired`);n=n.join(",");l=l.join(",");n=`return function (${n}) {\n`;
k&&(n+="var destructors = [];\n");var p=k?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(n+=`var thisWired = toClassParamWire(${p}, this);\n`);for(g=0;g<e;++g){var t=`toArg${g}Wire`;n+=`var arg${g}Wired = ${t}(${p}, arg${g});\n`;q.push(t)}n+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)n+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].L&&(n+=`${f}_dtor(${f});\n`,
q.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(q,n+"}\n"))(...d);return Eh(a,b)}
var ci=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},di=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Rb=(a,b,c,d,e,f,g,h)=>{var k=ci(c,d);b=W(b);b=di(b);f=Y(e,f);rh([],[a],l=>{function n(){Yh(`Cannot call ${p} due to unbound types`,k)}l=l[0];var p=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=l.v.constructor;void 0===q[b]?(n.ga=c-1,q[b]=n):(Gh(q,b,p),q[b].F[c-1]=n);rh([],k,t=>{t=bi(p,[t[0],null].concat(t.slice(1)),null,f,g,h);void 0===
q[b].F?(t.ga=c-1,q[b]=t):q[b].F[c-1]=t;if(l.v.wa)for(const u of l.v.wa)u.constructor.hasOwnProperty(b)||(u.constructor[b]=t);return[]});return[]})};Rb.g="vppippppii";
var Sb=(a,b,c,d,e,f)=>{var g=ci(b,c);e=Y(d,e);rh([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.v.ha&&(h.v.ha=[]);if(void 0!==h.v.ha[b-1])throw new X(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.v.ha[b-1]=()=>{Yh(`Cannot construct ${h.name} due to unbound types`,g)};rh([],g,l=>{l.splice(1,0,null);h.v.ha[b-1]=bi(k,l,null,e,f);
return[]});return[]})};Sb.g="vpipppp";
var Tb=(a,b,c,d,e,f,g,h,k)=>{var l=ci(c,d);b=W(b);b=di(b);f=Y(e,f);rh([],[a],n=>{function p(){Yh(`Cannot call ${q} due to unbound types`,l)}n=n[0];var q=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&n.v.hc.push(b);var t=n.v.fa,u=t[b];void 0===u||void 0===u.F&&u.className!==n.name&&u.ga===c-2?(p.ga=c-2,p.className=n.name,t[b]=p):(Gh(t,b,q),t[b].F[c-2]=p);rh([],l,v=>{v=bi(q,v,n,f,g,k);void 0===t[b].F?(v.ga=c-2,t[b]=v):t[b].F[c-2]=v;return[]});return[]})};Tb.g="vppippppiii";
var ei=(a,b,c)=>{if(!(a instanceof Object))throw new X(`${c} with invalid "this": ${a}`);if(!(a instanceof b.v.constructor))throw new X(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.s)throw new X(`cannot call emscripten binding method ${c} on deleted object`);return Kh(a.l.s,a.l.D.v,b.v)},Ub=(a,b,c,d,e,f,g,h,k,l)=>{b=W(b);e=Y(d,e);rh([],[a],n=>{n=n[0];var p=`${n.name}.${b}`,q={get(){Yh(`Cannot access ${p} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};q.set=
k?()=>Yh(`Cannot access ${p} due to unbound types`,[c,g]):()=>{throw new X(p+" is a read-only property");};Object.defineProperty(n.v.fa,b,q);rh([],k?[c,g]:[c],t=>{var u=t[0],v={get(){var L=ei(this,n,p+" getter");return u.B(e(f,L))},enumerable:!0};if(k){k=Y(h,k);var B=t[1];v.set=function(L){var M=ei(this,n,p+" setter"),H=[];k(l,M,B.I(H,L));kh(H)}}Object.defineProperty(n.v.fa,b,v);return[]});return[]})};Ub.g="vpppppppppp";
var fi=[],gi=[0,1,,1,null,1,!0,1,!1,1],tc=a=>{9<a&&0===--gi[a+1]&&(gi[a]=void 0,fi.push(a))};tc.g="vp";var Z=a=>{if(!a)throw new X(`Cannot use deleted val. handle = ${a}`);return gi[a]},Oh=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=fi.pop()||gi.length;gi[b]=a;gi[b+1]=1;return b}},hi={name:"emscripten::val",B:a=>{var b=Z(a);tc(a);return b},I:(a,b)=>Oh(b),R:lh,L:null},Vb=a=>qh(a,hi);Vb.g="vp";
var ii=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.B(y[d])}:function(d){return this.B(z[d])};case 2:return c?function(d){return this.B(A[d>>1])}:function(d){return this.B(C[d>>1])};case 4:return c?function(d){return this.B(D[d>>2])}:function(d){return this.B(E[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Wb=(a,b,c,d)=>{function e(){}b=W(b);e.values={};qh(a,{name:b,constructor:e,B:function(f){return this.constructor.values[f]},I:(f,g)=>g.value,R:ii(b,
c,d),L:null});Hh(b,e)};Wb.g="vpppi";var ji=(a,b)=>{var c=nh[a];if(void 0===c)throw a=`${b} has unknown type ${Xh(a)}`,new X(a);return c},Xb=(a,b,c)=>{var d=ji(a,"enum");b=W(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Eh(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d};Xb.g="vppi";
var ki=(a,b)=>{switch(b){case 4:return function(c){return this.B(Na[c>>2])};case 8:return function(c){return this.B(Oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Yb=(a,b,c)=>{b=W(b);qh(a,{name:b,B:d=>d,I:(d,e)=>e,R:ki(b,c),L:null})};Yb.g="vppp";var Zb=(a,b,c,d,e,f,g)=>{var h=ci(b,c);a=W(a);a=di(a);e=Y(d,e);Hh(a,function(){Yh(`Cannot call ${a} due to unbound types`,h)},b-1);rh([],h,k=>{Vh(a,bi(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};Zb.g="vpippppii";
var $b=(a,b,c,d,e)=>{b=W(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}qh(a,{name:b,B:f,I:(h,k)=>k,R:uh(b,c,0!==d),L:null})};$b.g="vpppii";var ac=(a,b,c)=>{function d(f){return new e(y.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=W(c);qh(a,{name:c,B:d,R:d},{Pb:!0})};ac.g="vpip";
var bc=(a,b)=>{b=W(b);qh(a,{name:b,B(c){var d=T(c+4,E[c>>2],!0);J(c);return d},I(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new X("Cannot pass non-string to std::string");var f=e?ng(d):d.length;var g=Ae(4+f+1),h=g+4;E[g>>2]=f;e?og(d,z,h,f+1):z.set(d,h);null!==c&&c.push(J,g);return g},R:lh,L(c){J(c)}})};bc.g="vpp";
var li=new TextDecoder("utf-16le"),mi=(a,b,c)=>{a>>=1;b=If(C,a,b/2,c);return li.decode(C.buffer instanceof ArrayBuffer?C.subarray(a,b):C.slice(a,b))},ni=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},oi=a=>2*a.length,pi=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},qi=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-
4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},ri=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},cc=(a,b,c)=>{c=W(c);if(2===b){var d=mi;var e=ni;var f=oi}else d=pi,e=qi,f=ri;qh(a,{name:c,B:g=>{var h=d(g+4,E[g>>2]*b,!0);J(g);return h},I:(g,h)=>{if("string"!=typeof h)throw new X(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=Ae(4+k+b);E[l>>2]=k/b;e(h,l+4,k+b);null!==g&&g.push(J,l);return l},
R:lh,L(g){J(g)}})};cc.g="vppp";var dc=(a,b,c,d,e,f)=>{jh[a]={name:W(b),Ra:Y(c,d),$:Y(e,f),ab:[]}};dc.g="vpppppp";var ec=(a,b,c,d,e,f,g,h,k,l)=>{jh[a].ab.push({Fb:W(b),Lb:c,na:Y(d,e),Kb:f,lc:g,kc:Y(h,k),mc:l})};ec.g="vpppppppppp";var fc=(a,b)=>{b=W(b);qh(a,{fb:!0,name:b,B:()=>{},I:()=>{}})};fc.g="vpp";var gc=(a,b,c,d)=>{function e(h){var k=T(a+36);hh(`'Could not load dynamic lib: ${k}\n${h}`);--Q;tf(()=>S(c)(a,d))}function f(){--Q;tf(()=>S(b)(a,d))}Q+=1;var g=ih(a,{J:!0});g?g.then(f,e):e()};gc.g="vpppp";
var hc=()=>{for(const a of Object.keys($e)){const b=Number(a);af.has(b)||Je(b)}};hc.g="v";function si(a){var b=ti,c=b.P.pop()||b.ea.length;b.ea[c]=a;return c}function ui(a){var b=ti;b.ea[a]=void 0;b.P.push(a)}class vi{ea=[void 0];P=[];get(a){return this.ea[a]}has(a){return void 0!==this.ea[a]}}
var ti=new vi,wi=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=si(a);return a},ic=(a,b,c)=>{const d=[];var e=wi();d.push(e.promise);Ge(e.id);for(const f of Object.keys($e)){const g=Number(f);g===a||af.has(g)||(e=wi(),Ie(g,e.id),bf[g]=e,d.push(e.promise))}Promise.all(d).then(()=>{bf={};S(b)(c)})};ic.g="vppp";function jc(){var a=Ae(4*(ma.length+1)),b=a;ma.forEach(c=>{var d=E,e=b>>2,f=ng(c)+1,g=Ae(f);g&&og(c,z,g,f);d[e]=g;b+=4});E[b>>2]=0;return a}jc.g="p";
var kc=a=>{Fa(a,!ba,1,!aa,262144,!1);Ga()};kc.g="vp";var Ha=a=>{"function"===typeof Atomics.waitAsync&&(Atomics.waitAsync(D,a>>2,a).value.then(Ka),Atomics.store(D,a+128>>2,1))};Ha.g="vp";var Ka=()=>tf(()=>{var a=ze();a&&(Ha(a),Oe())}),lc=(a,b)=>{a==b?setTimeout(Ka):r?postMessage({Ea:a,W:"checkMailbox"}):(a=$e[a])&&a.postMessage({W:"checkMailbox"})};lc.g="vpp";var xi=[],mc=(a,b,c,d,e)=>{d/=2;xi.length=d;c=e>>3;for(e=0;e<d;e++)xi[e]=F[c+2*e]?F[c+2*e+1]:Oa[c+2*e+1];return(b?cg[b]:yi[a])(...xi)};
mc.g="dippip";var nc=()=>{uf=!1;Q=0};nc.g="v";var oc=a=>{r?postMessage({W:"cleanupThread",Ta:a}):ef(a)};oc.g="vp";var pc=a=>{r?postMessage({W:"markAsFinished",Ta:a}):gf(a)};pc.g="vp";var qc=()=>{};qc.g="vp";var rc=()=>{throw new ra;};rc.g="v";
var zi=[],Ai=a=>{var b=zi.length;zi.push(a);return b},Bi=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=ji(E[b+4*d>>2],`parameter ${d}`);return c},Ci=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>2]=Oh(d));return a},Di={},Ei=a=>{var b=Di[a];return void 0===b?W(a):b},sc=(a,b,c)=>{var [d,...e]=Bi(a,b);b=d.I.bind(d);var f=e.map(k=>k.R.bind(k));a--;var g={toValue:Z};a=f.map((k,l)=>{var n=`argFromPtr${l}`;g[n]=k;return`${n}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";
break;case 3:h="";break;case 1:g.getStringOrSymbol=Ei,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.fb||(g.toReturnWire=b,g.emval_returnValue=Ci,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return Ai(Eh(h,c))};sc.g="pipi";
var Fi=globalThis,uc=a=>{if(!a)return Oh(Fi);a=Ei(a);return Oh(Fi[a])};uc.g="pp";var vc=a=>{a=Ei(a);return Oh(m[a])};vc.g="pp";var wc=(a,b)=>{a=Z(a);b=Z(b);return Oh(a[b])};wc.g="ppp";var xc=a=>{9<a&&(gi[a+1]+=1)};xc.g="vp";var yc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};yc.g="ipp";var zc=(a,b,c,d,e)=>zi[a](b,c,d,e);zc.g="dppppp";var Ac=a=>{a=Z(a);return"number"==typeof a};Ac.g="ip";var Bc=a=>{a=Z(a);return"string"==typeof a};Bc.g="ip";var Cc=a=>Oh(Ei(a));Cc.g="pp";
var Dc=a=>{var b=Z(a);kh(b);tc(a)};Dc.g="vp";var Ec=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};Ec.g="vppp";var Fc=a=>{a=Z(a);return Oh(typeof a)};Fc.g="pp";
function Gc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);D[b>>2]=a.getUTCSeconds();D[b+4>>2]=a.getUTCMinutes();D[b+8>>2]=a.getUTCHours();D[b+12>>2]=a.getUTCDate();D[b+16>>2]=a.getUTCMonth();D[b+20>>2]=a.getUTCFullYear()-1900;D[b+24>>2]=a.getUTCDay();D[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}Gc.g="vjp";var Gi=[0,31,60,91,121,152,182,213,244,274,305,335],Hi=[0,31,59,90,120,151,181,212,243,273,304,334];
function Hc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);D[b>>2]=a.getSeconds();D[b+4>>2]=a.getMinutes();D[b+8>>2]=a.getHours();D[b+12>>2]=a.getDate();D[b+16>>2]=a.getMonth();D[b+20>>2]=a.getFullYear()-1900;D[b+24>>2]=a.getDay();var c=a.getFullYear();D[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Hi:Gi)[a.getMonth()]+a.getDate()-1|0;D[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
D[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}Hc.g="vjp";function Ic(a,b,c,d,e,f,g){if(r)return R(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=V(d),k=FS.ka(h,a,e,b,c),l=k.s;D[f>>2]=k.ea;E[g>>2]=l;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return-n.A}}Ic.g="ipiiijpp";
function Jc(a,b,c,d,e,f){if(r)return R(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=V(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.ma(g,z.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.A}}Jc.g="ippiiij";
var Kc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(f,e);D[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(og(a,z,c,17),og(b,z,d,17)):(og(a,z,d,17),og(b,z,c,17))};Kc.g="vpppp";var Rc=()=>performance.timeOrigin+performance.now();Rc.g="d";var Nc=()=>Date.now();Nc.g="d";var Ii=1;
function Lc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Ii)a=performance.timeOrigin+performance.now();else return 52;F[c>>3]=BigInt(Math.round(1E6*a));return 0}Lc.g="iijp";var Mc=()=>{};Mc.g="v";var Oc=a=>w(T(a));Oc.g="vp";var Pc=()=>{Q+=1;throw"unwind";};Pc.g="v";var Qc=()=>z.length;Qc.g="p";var Sc=()=>navigator.hardwareConcurrency;Sc.g="i";var Tc=a=>{ui(a)};Tc.g="vp";
var Uc=(a,b,c)=>{a=ti.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(ti.get(c).promise);break;case 2:a.resolve(ti.get(c).promise);ui(c);break;case 3:a.reject(c)}};Uc.g="vpip";var Vc=()=>!1;Vc.g="ip";
var Ji={},Li=()=>{if(!Ki){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ji)void 0===Ji[b]?delete a[b]:a[b]=Ji[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ki=c}return Ki},Ki;function Wc(a,b){if(r)return R(19,1,a,b);var c=0,d=0,e;for(e of Li()){var f=b+c;E[a+d>>2]=f;c+=og(e,z,f,Infinity)+1;d+=4}return 0}Wc.g="ipp";
function Xc(a,b){if(r)return R(20,1,a,b);var c=Li();E[a>>2]=c.length;a=0;for(var d of c)a+=ng(d)+1;E[b>>2]=a;return 0}Xc.g="ipp";function Zc(a){if(r)return R(21,1,a);try{var b=V(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.A}}Zc.g="ii";
function $c(a,b){if(r)return R(22,1,a,b);try{var c=V(a),d=c.C?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;y[b]=d;A[b+2>>1]=0;F[b+8>>3]=BigInt(0);F[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.A}}$c.g="iip";
function ad(a,b,c,d){if(r)return R(23,1,a,b,c,d);try{a:{var e=V(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],k=E[a+4>>2];a+=8;var l=FS.read(e,y,h,k,f);if(0>l){var n=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}n=b}E[d>>2]=n;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.A}}ad.g="iippp";
function bd(a,b,c,d){if(r)return R(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=V(a);FS.llseek(e,b,c);F[d>>3]=BigInt(e.position);e.Ha&&0===b&&0===c&&(e.Ha=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.A}}bd.g="iijip";
function cd(a,b,c,d){if(r)return R(25,1,a,b,c,d);try{a:{var e=V(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],k=E[a+4>>2];a+=8;var l=FS.write(e,y,h,k,f);if(0>l){var n=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}n=b}E[d>>2]=n;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.A}}cd.g="iippp";function ed(...a){return I.heif_color_conversion_options_ext_copy(...a)}ed.G=!0;function fd(...a){return I.heif_color_conversion_options_ext_free(...a)}fd.G=!0;
function gd(...a){return I.heif_encoding_options_alloc(...a)}gd.G=!0;function hd(...a){return I.heif_encoding_options_free(...a)}hd.G=!0;function jd(...a){return I.heif_error_success(...a)}jd.G=!0;function kd(...a){return I.heif_image_get_bits_per_pixel_range(...a)}kd.G=!0;function ld(...a){return I.heif_image_get_chroma_format(...a)}ld.G=!0;function md(...a){return I.heif_image_get_nclx_color_profile(...a)}md.G=!0;function nd(...a){return I.heif_image_get_plane_readonly2(...a)}nd.G=!0;
function od(...a){return I.heif_image_release(...a)}od.G=!0;function pd(...a){return I.heif_nclx_color_profile_free(...a)}pd.G=!0;function qd(...a){return I.heif_tai_clock_info_release(...a)}qd.G=!0;function rd(...a){return I.heif_tai_timestamp_packet_alloc(...a)}rd.G=!0;function sd(...a){return I.heif_tai_timestamp_packet_copy(...a)}sd.G=!0;function td(...a){return I.heif_tai_timestamp_packet_release(...a)}td.G=!0;
function qe(a,b){try{return rg(z.subarray(a,a+b)),0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.A}}qe.g="ipp";var ta=a=>{var b=P(),c=Re(4),d=Re(4);Ue(a,c,d);a=E[c>>2];d=E[d>>2];c=T(a);J(a);if(d){var e=T(d);J(d)}O(b);return[c,e]};r||qf();
(()=>{var a={kb:Promise.resolve(),canHandle:b=>!m.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.kb=a.kb.then(async()=>{try{var d=await fg(b,{J:!0,qa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}yf[c]=d;return b})};xf.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{Gg(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Nc=Gg;FS.X=Array(4096);FS.mount(U,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));xg(FS.makedev(5,0),zg);xg(FS.makedev(6,0),Ag);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(rg(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:U.o.llseek};b.m={ja(c,d){c=+d;var e=V(c);c={parent:null,mount:{ib:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},ta(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Gb={MEMFS:U};
(()=>{let a=Dh.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Dh&&c instanceof Dh))return!1;var d=this.l.D.v,e=this.l.s;c.l=c.l;var f=c.l.D.v;for(c=c.l.s;d.M;)e=d.va(e),d=d.M;for(;f.M;)c=f.va(c),f=f.M;return d===f&&e===c},clone:function(){this.l.s||vh(this);if(this.l.ra)return this.l.count.value+=1,this;var c=zh,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ia:g.ia,ra:g.ra,s:g.s,D:g.D,K:g.K,S:g.S}}}));c.l.count.value+=1;c.l.ia=
!1;return c},["delete"](){this.l.s||vh(this);if(this.l.ia&&!this.l.ra)throw new X("Object already scheduled for deletion");yh(this);var c=this.l;--c.count.value;0===c.count.value&&(c.K?c.S.$(c.K):c.D.v.$(c.s));this.l.ra||(this.l.K=void 0,this.l.s=void 0)},isDeleted:function(){return!this.l.s},deleteLater:function(){this.l.s||vh(this);if(this.l.ia&&!this.l.ra)throw new X("Object already scheduled for deletion");Ah.push(this);1===Ah.length&&Ch&&Ch(Bh);this.l.ia=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(Uh.prototype,{Jb(a){this.lb&&(a=this.lb(a));return a},Xa(a){this.$?.(a)},R:lh,B:function(a){function b(){return this.Ba?Th(this.v.fa,{D:this.ec,s:c,S:this,K:a}):Th(this.v.fa,{D:this,s:a})}var c=this.Jb(a);if(!c)return this.Xa(a),null;var d=Sh(this.v,c);if(void 0!==d){if(0===d.l.count.value)return d.l.s=c,d.l.K=a,d.clone();d=d.clone();this.Xa(a);return d}d=this.v.Hb(c);d=Fh[d];if(!d)return b.call(this);d=this.Aa?d.Ab:d.pointerType;var e=Qh(c,this.v,d.v);return null===e?b.call(this):this.Ba?
Th(d.v.fa,{D:d,s:e,S:this,K:a}):Th(d.v.fa,{D:d,s:e})}});ff.push(()=>{Ji.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;Ji.VIPS_CONCURRENCY=1});
Wa.push(()=>{const a=Object.getOwnPropertyDescriptor(m.SourceCustom.prototype,"onRead");Object.defineProperty(m.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>Oh(c(d)))}});const b=Object.getOwnPropertyDescriptor(m.TargetCustom.prototype,"onWrite");Object.defineProperty(m.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(Dh.prototype,{preventAutoDelete:function(){const a=Ah.indexOf(this);-1<a&&Ah.splice(a,1);this.l.ia=!1;return this}});
if(!r){if(m.wasmMemory)za=m.wasmMemory;else{var Mi=m.INITIAL_MEMORY||1073741824;za=new WebAssembly.Memory({initial:Mi/65536,maximum:Mi/65536,shared:!0})}Ba()}m.preloadPlugins&&(xf=m.preloadPlugins);m.noExitRuntime&&(uf=m.noExitRuntime);m.print&&(la=m.print);m.printErr&&(w=m.printErr);m.dynamicLibraries&&(ma=m.dynamicLibraries);m.wasmBinary&&(na=m.wasmBinary);m.arguments&&(ca=m.arguments);m.thisProgram&&(da=m.thisProgram);if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.shift()();
m.ENV=Ji;m.addRunDependency=lf;m.removeRunDependency=kf;m.addFunction=Wf;m.FS_preloadFile=Gg;m.FS_unlink=(...a)=>FS.unlink(...a);m.FS_createPath=(...a)=>FS.createPath(...a);m.FS_createDevice=(...a)=>FS.createDevice(...a);m.FS=FS;m.FS_createDataFile=(...a)=>FS.createDataFile(...a);m.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);m.setAutoDeleteLater=a=>{wh=a};m.deletionQueue=Ah;m.setDelayFunction=a=>{Ch=a;Ah.length&&Ch&&Ch(Bh)};m.incrementExceptionRefcount=a=>Se(a);
m.decrementExceptionRefcount=a=>Te(a);m.getExceptionMessage=a=>ta(a);var yi=[pe,vf,bh,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Ic,Jc,Wc,Xc,Zc,$c,ad,bd,cd],cg={};function Ni(a){for(var b=C[a+6>>1];13===b&&!(16<E[a>>2]);){var c=E[a+8>>2],d=E[c>>2];if(0===d){b=0;break}else if(0===E[(c>>2)+1])a=d,b=C[d+6>>1];else break}return[a,b]}
function dd(a,b,c,d){var e=E[(a>>2)+1],f=E[(a>>2)+6],g=E[(a>>2)+2],h=E[(a>>2)+5];a=Ni(E[(a>>2)+3])[1];var k=P(),l=k,n=[],p=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)n.push(c),p=!0;for(var q=0;q<f;q++){var t=E[(d>>2)+q],u=Ni(E[(g>>2)+q]),v=u[0];u=u[1];switch(u){case 1:case 10:case 9:n.push(E[t>>2]);break;case 2:n.push(Na[t>>2]);break;case 3:n.push(Oa[t>>3]);break;case 5:n.push(z[t]);break;case 6:n.push(y[t]);break;case 7:n.push(C[t>>
1]);break;case 8:n.push(A[t>>1]);break;case 11:case 12:n.push(Pa[t>>3]);break;case 4:n.push(Pa[t>>3]);n.push(Pa[(t>>3)+1]);break;case 13:u=E[v>>2];v=C[v+4>>1];l-=u;l&=~(v-1);y.subarray(l,l+u).set(y.subarray(t,t+u));n.push(l);break;case 14:n.push(E[t>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(q=e-1;q>=f;q--)switch(t=E[(d>>2)+q],u=Ni(E[(g>>2)+q]),v=u[0],u=u[1],u){case 5:case 6:--l;l&=-1;z[l]=z[t];break;case 7:case 8:l-=2;l&=
-2;C[l>>1]=C[t>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;E[l>>2]=E[t>>2];break;case 3:case 11:case 12:l-=8;l&=-8;E[l>>2]=E[t>>2];E[(l>>2)+1]=E[(t>>2)+1];break;case 4:l-=16;l&=-8;E[l>>2]=E[t>>2];E[(l>>2)+1]=E[(t>>2)+1];E[(l>>2)+2]=E[(t>>2)+2];E[(l>>2)+3]=E[(t>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,t,E[v>>2],C[v+4>>1]]);break;case 14:l-=4;l&=-4;E[l>>2]=E[t>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}n.push(l);for(q=0;q<h.length;q++)e=
h[q],d=e[0],t=e[1],u=e[2],v=e[3],l-=u,l&=~(v-1),y.subarray(l,l+u).set(y.subarray(t,t+u)),E[d>>2]=l}O(l);Re(0);b=S(b).apply(null,n);O(k);if(!p)switch(a){case 0:break;case 1:case 9:case 10:E[c>>2]=b;break;case 2:Na[c>>2]=b;break;case 3:Oa[c>>3]=b;break;case 5:case 6:z[c+0]=b;break;case 7:case 8:C[c>>1]=b;break;case 11:case 12:Pa[c>>3]=b;break;case 14:E[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}dd.g="viiii";
var ye,Ia,ze,Ae,J,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Fa,La,Le,Me,Ne,Oe,K,Pe,Qe,O,Re,P,Se,Te,Ue,Ve,We;m.___THREW__=1328;m.__ZTISt12length_error=1442696;m.__ZTVSt12length_error=1442676;m.__ZTVN10__cxxabiv120__si_class_type_infoE=1442368;m.__ZTVN10__cxxabiv117__class_type_infoE=1442328;m.__ZTISt20bad_array_new_length=1442568;m.___threwValue=1332;m._stdout=1428208;m._stderr=1428056;m._g_mem_gc_friendly=3364540;m._g_utf8_skip=1371028;m.__ZTVNSt3__215basic_streambufIcNS_11char_traitsIcEEEE=1445792;
m.__ZTVNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1446200;m.__ZTTNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1446616;m.__ZTTNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1446848;m.__ZTVNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1446556;m.__ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1446808;m.__ZNSt3__24coutE=3415120;m.__ZNSt3__24cerrE=3415296;m.__ZNSt3__25ctypeIcE2idE=3412328;
m.__ZTINSt3__219__shared_weak_countE=1442852;m.__ZTVNSt3__212bad_weak_ptrE=1442876;m.__ZTINSt3__212bad_weak_ptrE=1442896;m.__ZSt7nothrow=947108;m.__ZTISt12out_of_range=1442728;m.__ZTVSt12out_of_range=1442708;m.__ZTVN10__cxxabiv121__vmi_class_type_infoE=1442420;var I;function Qd(a,b){var c=P();try{S(a)(b)}catch(d){O(c);if(!(d instanceof x))throw d;K(1,0)}}function Yd(a,b,c,d){var e=P();try{S(a)(b,c,d)}catch(f){O(e);if(!(f instanceof x))throw f;K(1,0)}}
function Bd(a,b,c){var d=P();try{return S(a)(b,c)}catch(e){O(d);if(!(e instanceof x))throw e;K(1,0)}}function Pd(a){var b=P();try{S(a)()}catch(c){O(b);if(!(c instanceof x))throw c;K(1,0)}}function Ad(a,b){var c=P();try{return S(a)(b)}catch(d){O(c);if(!(d instanceof x))throw d;K(1,0)}}function zd(a){var b=P();try{return S(a)()}catch(c){O(b);if(!(c instanceof x))throw c;K(1,0)}}function fe(a,b,c,d,e,f){var g=P();try{S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}
function Dd(a,b,c,d){var e=P();try{return S(a)(b,c,d)}catch(f){O(e);if(!(f instanceof x))throw f;K(1,0)}}function ee(a,b,c,d,e){var f=P();try{S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0)}}function Gd(a,b,c,d,e,f){var g=P();try{return S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}function Td(a,b,c){var d=P();try{S(a)(b,c)}catch(e){O(d);if(!(e instanceof x))throw e;K(1,0)}}
function Hd(a,b,c,d,e,f,g){var h=P();try{return S(a)(b,c,d,e,f,g)}catch(k){O(h);if(!(k instanceof x))throw k;K(1,0)}}function Ed(a,b,c,d,e){var f=P();try{return S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0)}}function xd(a,b,c,d,e,f){var g=P();try{return S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}function wd(a,b,c,d){var e=P();try{return S(a)(b,c,d)}catch(f){O(e);if(!(f instanceof x))throw f;K(1,0)}}
function Ud(a,b,c,d){var e=P();try{S(a)(b,c,d)}catch(f){O(e);if(!(f instanceof x))throw f;K(1,0)}}function Vd(a,b,c,d,e){var f=P();try{S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0)}}function Cd(a,b,c,d){var e=P();try{return S(a)(b,c,d)}catch(f){O(e);if(!(f instanceof x))throw f;K(1,0)}}function Rd(a,b,c){var d=P();try{S(a)(b,c)}catch(e){O(d);if(!(e instanceof x))throw e;K(1,0)}}function ud(a,b){var c=P();try{return S(a)(b)}catch(d){O(c);if(!(d instanceof x))throw d;K(1,0)}}
function ke(a,b,c,d,e,f,g,h,k,l,n){var p=P();try{S(a)(b,c,d,e,f,g,h,k,l,n)}catch(q){O(p);if(!(q instanceof x))throw q;K(1,0)}}function ge(a,b,c,d,e,f,g){var h=P();try{S(a)(b,c,d,e,f,g)}catch(k){O(h);if(!(k instanceof x))throw k;K(1,0)}}function he(a,b,c,d,e,f,g,h){var k=P();try{S(a)(b,c,d,e,f,g,h)}catch(l){O(k);if(!(l instanceof x))throw l;K(1,0)}}function vd(a,b,c){var d=P();try{return S(a)(b,c)}catch(e){O(d);if(!(e instanceof x))throw e;K(1,0)}}
function Xd(a,b,c,d,e){var f=P();try{S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0)}}function Zd(a,b,c,d,e){var f=P();try{S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0)}}function Sd(a,b,c,d,e){var f=P();try{S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0)}}function be(a,b,c,d,e,f,g,h){var k=P();try{S(a)(b,c,d,e,f,g,h)}catch(l){O(k);if(!(l instanceof x))throw l;K(1,0)}}
function $d(a,b,c,d,e,f,g,h,k,l){var n=P();try{S(a)(b,c,d,e,f,g,h,k,l)}catch(p){O(n);if(!(p instanceof x))throw p;K(1,0)}}function ae(a,b,c,d,e,f,g,h,k){var l=P();try{S(a)(b,c,d,e,f,g,h,k)}catch(n){O(l);if(!(n instanceof x))throw n;K(1,0)}}function de(a,b,c,d,e,f){var g=P();try{S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}function ce(a,b,c,d,e,f,g){var h=P();try{S(a)(b,c,d,e,f,g)}catch(k){O(h);if(!(k instanceof x))throw k;K(1,0)}}
function me(a,b,c,d,e,f,g,h,k,l,n,p,q){var t=P();try{S(a)(b,c,d,e,f,g,h,k,l,n,p,q)}catch(u){O(t);if(!(u instanceof x))throw u;K(1,0)}}function le(a,b,c,d,e,f,g,h,k,l,n,p){var q=P();try{S(a)(b,c,d,e,f,g,h,k,l,n,p)}catch(t){O(q);if(!(t instanceof x))throw t;K(1,0)}}function je(a,b,c,d,e,f,g,h,k,l){var n=P();try{S(a)(b,c,d,e,f,g,h,k,l)}catch(p){O(n);if(!(p instanceof x))throw p;K(1,0)}}
function ie(a,b,c,d,e,f,g,h,k){var l=P();try{S(a)(b,c,d,e,f,g,h,k)}catch(n){O(l);if(!(n instanceof x))throw n;K(1,0)}}function ne(a,b,c,d,e,f,g,h,k,l,n,p,q,t){var u=P();try{S(a)(b,c,d,e,f,g,h,k,l,n,p,q,t)}catch(v){O(u);if(!(v instanceof x))throw v;K(1,0)}}function Wd(a,b,c,d,e,f){var g=P();try{S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}function Id(a,b,c,d,e,f,g,h){var k=P();try{return S(a)(b,c,d,e,f,g,h)}catch(l){O(k);if(!(l instanceof x))throw l;K(1,0)}}
function Nd(a,b){var c=P();try{return S(a)(b)}catch(d){O(c);if(!(d instanceof x))throw d;K(1,0);return 0n}}function Ld(a,b,c,d,e,f,g,h,k,l,n,p,q){var t=P();try{return S(a)(b,c,d,e,f,g,h,k,l,n,p,q)}catch(u){O(t);if(!(u instanceof x))throw u;K(1,0)}}function Od(a,b,c,d,e){var f=P();try{return S(a)(b,c,d,e)}catch(g){O(f);if(!(g instanceof x))throw g;K(1,0);return 0n}}function yd(a,b,c,d){var e=P();try{return S(a)(b,c,d)}catch(f){O(e);if(!(f instanceof x))throw f;K(1,0)}}
function Jd(a,b,c,d,e,f,g,h,k,l,n){var p=P();try{return S(a)(b,c,d,e,f,g,h,k,l,n)}catch(q){O(p);if(!(q instanceof x))throw q;K(1,0)}}function Kd(a,b,c,d,e,f,g,h,k,l,n,p){var q=P();try{return S(a)(b,c,d,e,f,g,h,k,l,n,p)}catch(t){O(q);if(!(t instanceof x))throw t;K(1,0)}}function oe(a,b,c,d,e,f,g,h,k,l,n,p,q,t,u,v){var B=P();try{S(a)(b,c,d,e,f,g,h,k,l,n,p,q,t,u,v)}catch(L){O(B);if(!(L instanceof x))throw L;K(1,0)}}
function Md(a,b,c,d,e,f){var g=P();try{return S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}function Fd(a,b,c,d,e,f){var g=P();try{return S(a)(b,c,d,e,f)}catch(h){O(g);if(!(h instanceof x))throw h;K(1,0)}}function Oi(a=[]){var b=bg("main").Sa;if(b){a.unshift(da);var c=a.length,d=Re(4*(c+1)),e=d;a.forEach(g=>{E[e>>2]=pg(g);e+=4});E[e>>2]=0;try{var f=b(c,d);Yc(f,!0)}catch(g){Ye(g)}}}
function Da(a=ca){function b(){m.calledRun=!0;if(!pa&&(Ta(),ua?.(m),m.onRuntimeInitialized?.(),m.noInitialRun||Oi(a),!r)){if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var c=m.postRun.shift();Gf.push(c)}Ua(Gf)}}if(0<hf)jf=Da;else if(r)ua?.(m),Ta();else{if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)ff.push(m.preRun.shift());Ua(ff);0<hf?jf=Da:m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),
1);b()},1)):b()}}var Va;r||(Va=await (Ca()),Da());Qa?moduleRtn=m:moduleRtn=new Promise((a,b)=>{ua=a;va=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);var isPthread=globalThis.self?.name?.startsWith("em-pthread");isPthread&&Vips();
